name: test_Django
# The workflow runs when there a pull request is made to the main branch.
on:
  pull_request:
    branches: [main]
env:
  DEBUG: "1"
  SECRET_KEY: ${{ env.SECRET_KEY }}
  DB_NAME: ${{ env.DB_NAME }}
  DB_USER: ${{ env.DB_USER }}
  DB_PASSWORD: ${{ env.DB_PASSWORD }}
  DB_HOST: ${{ env.DB_HOST }}
  ALLOWED_HOSTS: ${{ env.AlLOWED_HOSTS }} 
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt 
      - run: python ./swe574/manage.py test
