name: test_Django
# The workflow runs when there a pull request is made to the main branch.
on:
  pull_request:
    branches: [main]
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt 
      - run: python ./swe574/manage.py test